/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>

#ifndef __lcm_t_headers_pcl_pointcloud_float_t_hpp__
#define __lcm_t_headers_pcl_pointcloud_float_t_hpp__

#include <vector>

namespace lcm_t_headers
{

class pcl_pointcloud_float_t
{
    public:
        int64_t    timestamp;
        int32_t    floatXYZ_size;
        std::vector< float > floatXYZ;
        int32_t    floatXYZRGB_size;
        std::vector< float > floatXYZRGB;

    public:
        inline int encode(void *buf, int offset, int maxlen) const;
        inline int getEncodedSize() const;
        inline int decode(const void *buf, int offset, int maxlen);
        inline static int64_t getHash();
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static int64_t _computeHash(const __lcm_hash_ptr *p);
};

int pcl_pointcloud_float_t::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int pcl_pointcloud_float_t::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int pcl_pointcloud_float_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t pcl_pointcloud_float_t::getHash()
{
    static int64_t hash = _computeHash(NULL);
    return hash;
}

const char* pcl_pointcloud_float_t::getTypeName()
{
    return "pcl_pointcloud_float_t";
}

int pcl_pointcloud_float_t::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->floatXYZ_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->floatXYZ[0], this->floatXYZ_size);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->floatXYZRGB_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __float_encode_array(buf, offset + pos, maxlen - pos, &this->floatXYZRGB[0], this->floatXYZRGB_size);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int pcl_pointcloud_float_t::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->floatXYZ_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->floatXYZ.resize(this->floatXYZ_size);
    if(this->floatXYZ_size) {
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->floatXYZ[0], this->floatXYZ_size);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->floatXYZRGB_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    this->floatXYZRGB.resize(this->floatXYZRGB_size);
    if(this->floatXYZRGB_size) {
        tlen = __float_decode_array(buf, offset + pos, maxlen - pos, &this->floatXYZRGB[0], this->floatXYZRGB_size);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int pcl_pointcloud_float_t::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int64_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->floatXYZ_size);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __float_encoded_array_size(NULL, this->floatXYZRGB_size);
    return enc_size;
}

int64_t pcl_pointcloud_float_t::_computeHash(const __lcm_hash_ptr *)
{
    int64_t hash = 0xd3459a931392739bLL;
    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
